# Generated by Django 4.0.3 on 2022-03-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.CharField(max_length=30, unique=True, verbose_name='项目名称')),
                ('project_desc', models.CharField(max_length=500, verbose_name='项目描述')),
                ('QAPL', models.CharField(max_length=25, verbose_name='QAPL')),
                ('project_manager', models.CharField(max_length=25, verbose_name='项目经理')),
                ('product_manager', models.CharField(max_length=25, verbose_name='产品经理')),
                ('EPL', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'Project_Infor',
            },
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_type', models.SmallIntegerField(choices=[(0, 'NVR'), (1, 'IPC'), (2, 'PTZ')], default=1, verbose_name='产品类型')),
                ('SKU', models.CharField(max_length=20, unique=True, verbose_name='产品型号')),
                ('SKU_name', models.CharField(max_length=30, null=True, verbose_name='产品名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projectinformation')),
            ],
            options={
                'verbose_name': '产品信息',
                'db_table': 'Product_Infor',
            },
        ),
        migrations.CreateModel(
            name='FWList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version_information', models.CharField(max_length=40, unique=True, verbose_name='版本号')),
                ('FW_location', models.CharField(max_length=40, unique=True, verbose_name='软件保存位置')),
                ('releasenote_location', models.CharField(max_length=40, unique=True, verbose_name='软件保存位置')),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.productinformation')),
            ],
            options={
                'verbose_name': '软件版本信息',
                'db_table': 'FW_List',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('certification_type', models.CharField(max_length=10, unique=True, verbose_name='认证类型')),
                ('certification_report', models.CharField(max_length=40, unique=True, verbose_name='报告')),
                ('certification_location', models.CharField(max_length=40, unique=True, verbose_name='文件保存位置')),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.productinformation')),
            ],
            options={
                'verbose_name': '证书信息',
                'db_table': 'Certification_Infor',
            },
        ),
    ]
